name: sphinx

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - xuefan
   pull_request:
     branches:
       - xuefan

jobs:
  sphinx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9


    - name: conda environment
      run: |
        pip install sphinx
    - name: Build sphinx documentation
      run: |
        sphinx-build -b html docs docs/html